# Generated by Django 3.2.4 on 2021-06-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_num', models.IntegerField(default=0)),
                ('head_num', models.IntegerField(default=0)),
                ('p_num', models.IntegerField(default=0)),
                ('div_num', models.IntegerField(default=0)),
            ],
        ),
    ]
