# Generated by Django 3.2.4 on 2021-07-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTestTask', '0002_auto_20210702_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstring',
            name='url_path',
            field=models.CharField(default='', max_length=300),
        ),
    ]
