# Generated by Django 3.2.4 on 2021-07-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTestTask', '0004_urlstring_url_path_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlstring',
            name='url_path_test',
        ),
    ]
