# Generated by Django 3.2.4 on 2021-07-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTestTask', '0006_urlstring_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstring',
            name='url_path',
            field=models.URLField(default='', max_length=300),
        ),
    ]
